STEP AP214 and VRML FreeCAD script generator
============================================
:Author:    Maurice
:Email:     https://launchpad.net/~easyw
:Date:      August 2015
:Revision:  1.3.1
:website: https://github.com/easyw/kicad-3d-models-in-freecad/
:docname: README.txt

this repository +
link:https://github.com/easyw/kicad-3d-models-in-freecad/[] +
is a place to find STEP AP214 3D models and VRML kicad 3D models
under *''cadquery'' DIR*, there are some nice scripts that can generate +
*STEP and VRML parametric models* for +
*GullWings ICs, DIP ICS, Chip Capacitors, Chip resistors, pin-strip headers*

All the STEP and VRML models can be used with kicad new stable release (August 2015)
and are ready to be used with Kicad StepUp script +
*kicad StepUp* is a new approach to export kicad board and modules in STEP AP214 (with colors).
With kicad StepUp it is possible to export the 3D board and modules in STEP
for MCAD interchange and create the 3D wrl libraries. +
link:http://sourceforge.net/projects/kicadstepup/[kicadStepUp at sourceforge] +
link:http://bazaar.launchpad.net/~easyw/kicad-stepup/trunk/files/[kicadStepUp at lauchpad] +
link:http://youtu.be/Ukd47VXYzQU[YouTube Kicad StepUp demo video]

<<<

.OverView of the parametric scripts
**********************************************************************
this repository +
link:https://github.com/easyw/kicad-3d-models-in-freecad/[] +
is a place to find STEP AP214 3D models and VRML kicad 3D models; +
under *''cadquery'' DIR*, there are some nice scripts that can generate +
*STEP and VRML parametric models* for +
*GullWings ICs, DIP ICS, Chip Capacitors, Chip resistors, pin-strip headers* ready to go for *kicad StepUp script*

The parametric scripts are derived from CadQuery scripts for generating QFP, DIP and pinHeaders
models in X3D format. +
author *hyOzd* +
author site:  link:https://bitbucket.org/hyOzd/freecad-macros/[]

## requirements ## +
link:https://github.com/jmwright/cadquery-freecad-module/[] version 0.18 or later +
link:http://freecadweb.org/[] version 0.15 or later +
*Note:* at the moment all the scripts are tested in Windows... +
        work in progress for Linux

**********************************************************************
Running the scripts
-------------------

to run the script just do: +
freecad make_gw_export_fc.py modelName +
examples: +
- c:\freecad\bin\freecad make_gw_export_fc.py SOIC_8 +
- c:\freecad\bin\freecad make_gw_export_fc.py all

modelName and parameters are described in: +
1. cq_params_gw_soic.py file for defining SOIC mechanical data +
2. cq_params_gw_qfp.py file for defining QFP mechanical data +
3. cq_params_gw_ssop.py file for defining SSOP mechanical data +
4. cq_params_gw_tssop.py file for defining TSSOP mechanical data +
5. cq_params_gw_sot.py file for defining SOT mechanical data +
all data in parameter files are collected from components data sheets +
##the script will generate STEP and VRML parametric models##
ready to be used with kicad StepUp script 


credits
-------

author *hyOzd* +
author site:  link:https://bitbucket.org/hyOzd/freecad-macros/[] +
FreeCAD & cadquery tools: +
libraries to export generated models in STEP & VRML format +
- cad tools functions +
Copyright (c) 2015 *Maurice* link:https://launchpad.net/~easyw[] +

[[copyright]]
Copyright
---------

This document '{docname}' and all the materials and files at the repository are +
Copyrighted © 2015 by {Author}. +
You may distribute it and/or modify it under the terms of either
the GNU General Public License  (http://www.gnu.org/licenses/gpl.html),
version 3 or later, or the Creative Commons Attribution License
(http://creativecommons.org/licenses/by/3.0/), version 3.0 or later.

All trademarks within this guide belong to their legitimate owners.

Risk disclaimer
---------------

*USE 3D CAD DATA AT YOUR OWN RISK +
DO NOT RELY UPON ANY INFORMATION FOUND HERE WITHOUT INDEPENDENT VERIFICATION.*
