STEP AP214 and VRML FreeCAD script generator
============================================
:Author:    Maurice
:Email:     https://launchpad.net/~easyw
:Date:      August 2015
:Revision:  1.3.1
:website: https://github.com/easyw/kicad-3d-models-in-freecad/
:docname: README.txt

this repository +
link:https://github.com/easyw/kicad-3d-models-in-freecad/[] +
is a place to find STEP AP214 3D models and VRML kicad 3D models
under *''cadquery'' DIR*, there are some nice scripts that can generate +
*STEP and VRML parametric models* for +
*GullWings ICs, DIP ICS, Chip Capacitors, Chip resistors, pin-strip headers*

All the STEP and VRML models can be used with kicad new stable release (August 2015)
and are ready to be used with Kicad StepUp script +
*kicad StepUp* is a new approach to export kicad board and modules in STEP AP214 (with colors).
With kicad StepUp it is possible to export the 3D board and modules in STEP
for MCAD interchange and create the 3D wrl libraries. +
link:http://sourceforge.net/projects/kicadstepup/[kicadStepUp at sourceforge] +
link:http://bazaar.launchpad.net/~easyw/kicad-stepup/trunk/files/[kicadStepUp at lauchpad] +
link:http://youtu.be/Ukd47VXYzQU[YouTube Kicad StepUp demo video]

<<<

.OverView of the parametric scripts
**********************************************************************
this repository +
link:https://github.com/easyw/kicad-3d-models-in-freecad/[] +
is a place to find *STEP AP214 3D models and VRML kicad 3D models*; +
under *''cadquery'' DIR*, there are some nice scripts that can generate +
*STEP and VRML parametric models* for +
*SOIC, SSOP, TSSOP, SOT, QFP ... (GullWings in general), QFN ICs, DIP ICS, Chip Capacitors, Chip resistors, pin-strip headers* ready to go for *kicad StepUp script* +
and *ready to go* 3D STEP and VRML models. +
The parametric scripts are derived from CadQuery scripts for generating QFP, DIP and pinHeaders
models in X3D format. +
author hyOzd +
author site:  bitbucket.org/hyOzd/freecad-macros/

## requirements ## +
link:https://github.com/jmwright/cadquery-freecad-module/archive/v0.2.0.zip/[CadQuery module] version 0.20 or later +
link:http://freecadweb.org/[FreeCAD] version 0.15 or later (use only STABLE versions)

**********************************************************************
Running the scripts
-------------------

to run the script just move to the scripts dir and do: +
freecad ./make_gw_export_fc.py modelName +
examples in win: +
+c:\freecad\bin\freecad make_gw_export_fc.py SOIC_8+ +
+c:\freecad\bin\freecad make_gw_export_fc.py all+ +
in linux: +
+freecad ./make_gw_export_fc.py SOIC_8+ +
+freecad ./make_gw_export_fc.py all+

modelName and parameters are described in: +
1. cq_params_gw_soic.py file for defining SOIC mechanical data +
2. cq_params_gw_qfp.py file for defining QFP mechanical data +
3. cq_params_gw_ssop.py file for defining SSOP mechanical data +
4. cq_params_gw_tssop.py file for defining TSSOP mechanical data +
5. cq_params_gw_sot.py file for defining SOT mechanical data +
6. cq_params_chip_cap.py file for defining chip capacitors mechanical data +
7. cq_params_chip_res.py file for defining chip resistors mechanical data +
all data in parameter files are collected from components data sheets +
##the script will generate STEP and VRML parametric models##
ready to be used with kicad StepUp script

[red]*Note:* You may get a 'No module named QtNetwork' error on Ubuntu based systems when you select the module in FreeCAD.
If you do, run the following command line from a terminal to fix this issue. +
+sudo apt-get install python-pyside.qtnetwork+

[CAUTION]
====
For Debian users, because of some lib issues, FreeCAD fusion may result with monocrome objects
link:http://www.freecadweb.org/wiki/index.php?title=Download#Development_Versions[FreeCAD in Debian] +
to build your models you may consider to run FreeCAD in Lubuntu under virtualbox in Debian systems
====


credits
-------

Author and Copyright (c) 2015 *Maurice* link:https://launchpad.net/~easyw[] +
FreeCAD & cadquery tools: +
libraries to export generated models in STEP & VRML format +
- cad tools functions +
- routines to build modules +

author 'hyOzd' +
basic freecad macros - author site:  bitbucket.org/hyOzd/freecad-macros/ +

[[copyright]]
Copyright
---------

This document '{docname}' and all the materials and files at the repository are
Copyrighted © 2015 by {Author}. +
You may distribute it and/or modify it under the terms of either
the GNU General Public License  (http://www.gnu.org/licenses/gpl.html),
version 3 or later, or the Creative Commons Attribution License
(http://creativecommons.org/licenses/by/3.0/), version 3.0 or later.

All trademarks within this guide belong to their legitimate owners.

Risk disclaimer
---------------

*USE 3D CAD DATA AT YOUR OWN RISK +
DO NOT RELY UPON ANY INFORMATION FOUND HERE WITHOUT INDEPENDENT VERIFICATION.*
